const affirmations = [
    "You are capable of achieving great things.",
    "Believe in yourself and all that you are.",
    "Every day is a new opportunity to grow and improve.",
    "You have the power to create the life you desire.",
    "You are worthy of love and respect.",
    "Embrace your uniqueness; you are one of a kind.",
    "You have the strength to overcome any challenge.",
    "Your potential is limitless.",
    "Be kind to yourself and others.",
    "Your positive attitude brings good things into your life.",
    "You are enough just as you are.",
    "You are deserving of happiness and success.",
    "You are resilient and can handle anything.",
    "Believe in the power of your dreams.",
    "You are surrounded by love and support.",
    "Every step you take brings you closer to your goals.",
    "You are a work in progress, and that's okay.",
    "Your hard work and dedication will pay off.",
    "You are a source of inspiration to others.",
    "You have the ability to make a positive impact.",
    "Your courage is admirable.",
    "You are a beautiful person inside and out.",
    "You are constantly growing and evolving.",
    "You are in control of your own happiness.",
    "You have the power to change your story.",
    "You are a valuable and important person.",
    "You have a lot to offer the world.",
    "You are capable of amazing things.",
    "You are worthy of all the good things in life.",
    "You are a beacon of light and hope.",
    "You are strong, brave, and resilient.",
    "You have the power to make today a great day.",
    "You are full of potential and possibilities.",
    "You are exactly where you need to be right now.",
    "You are enough just as you are.",
    "You have the power to create positive change.",
    "You are loved and appreciated.",
    "You have a kind and compassionate heart.",
    "You are a source of joy and happiness.",
    "You are capable of handling whatever comes your way.",
    "You are making a difference in the world.",
    "You are strong, capable, and resilient.",
    "You have the power to achieve your dreams.",
    "You are deserving of all the love and happiness in the world.",
    "You are constantly learning and growing.",
    "You are a wonderful person.",
    "You have a bright future ahead of you.",
    "You are a positive force in the world.",
    "You are capable of overcoming any obstacle.",
    "You are worthy of all the good things in life.",
    "You are loved and valued.",
    "You have the strength to keep going.",
    "You are a unique and special individual.",
    "You are deserving of success and happiness.",
    "You are full of creativity and ideas.",
    "You have the power to make your dreams a reality.",
    "You are a wonderful person just the way you are.",
    "You have the ability to achieve great things.",
    "You are a light in the world.",
    "You are strong, confident, and capable.",
    "You are braver than you believe.",
    "You are more talented than you know.",
    "You are capable of more than you imagine.",
    "You are a positive thinker.",
    "You bring light to those around you.",
    "You have a positive and inspiring impact.",
    "You are loved beyond measure.",
    "You are a magnet for miracles.",
    "You are a beautiful person, inside and out.",
    "You are a wonderful friend.",
    "You are a joy to be around.",
    "You are a source of light and inspiration.",
    "You are a positive influence on others.",
    "You have the ability to brighten someone's day.",
    "You are a wonderful person with many talents.",
    "You are a valuable friend.",
    "You are a positive and powerful force in the world.",
    "You are loved for who you are.",
    "You are a beacon of hope.",
    "You are a source of strength.",
    "You are a blessing to those around you.",
    "You are a source of inspiration and positivity.",
    "You have the power to uplift others.",
    "You are capable of achieving your dreams.",
    "You are a valuable and cherished person.",
    "You are a beautiful soul.",
    "You are a positive light in the world.",
    "You are capable of overcoming any challenge.",
    "You are a strong and capable individual.",
    "You have a bright future ahead.",
    "You are an amazing person.",
    "You are full of potential.",
    "You are a positive and inspiring person.",
    "You are a wonderful individual.",
    "You are capable of great things.",
    "You are worthy of all the love and happiness in the world.",
    "You are a positive and influential person.",
    "You are a source of joy and happiness.",
    "You are a positive thinker and doer.",
    "You are capable of achieving anything you set your mind to.",
    "You are a blessing to those around you.",
    "You are an inspiration to others.",
    "You are capable of great things.",
    "You are a wonderful person with a kind heart.",
    "You are a source of love and positivity.",
    "You are a bright light in the world.",
    "You are a positive influence on those around you.",
    "You are a wonderful person who deserves the best.",
    "You are a positive and powerful force in the world.",
    "You are a source of hope and inspiration.",
    "You are a valuable and cherished person.",
    "You are a source of joy and happiness.",
    "You are capable of achieving your dreams.",
    "You are a wonderful individual.",
    "You are full of potential and possibilities.",
    "You are a positive and inspiring person.",
    "You are a source of light and love.",
    "You are a valuable and important person.",
    "You are a positive force in the world.",
    "You are a wonderful person who deserves the best.",
    "You are a source of inspiration and positivity.",
    "You are capable of great things.",
    "You are a strong and capable individual.",
    "You have the power to uplift others.",
    "You are a bright light in the world.",
    "You are a source of strength and hope.",
    "You are a blessing to those around you.",
    "You are a positive influence on others.",
    "You are a wonderful friend.",
    "You are a source of light and inspiration.",
    "You are a positive thinker.",
    "You are braver than you believe.",
    "You are more talented than you know.",
    "You are capable of more than you imagine.",
    "You are a positive and powerful force in the world.",
    "You are a wonderful person with many talents.",
    "You are a valuable friend.",
    "You are a source of joy and happiness.",
    "You are a positive influence on those around you.",
    "You have the ability to brighten someone's day.",
    "You are a wonderful person just the way you are.",
    "You have the power to make your dreams a reality.",
    "You are full of creativity and ideas.",
    "You are deserving of success and happiness.",
    "You are a unique and special individual.",
    "You have the strength to keep going.",
    "You are loved and valued.",
    "You are capable of overcoming any obstacle.",
    "You are a positive force in the world.",
    "You have a bright future ahead of you.",
    "You are a wonderful person.",
    "You are constantly learning and growing.",
    "You are deserving of all the love and happiness in the world.",
    "You have the power to achieve your dreams.",
    "You are strong, capable, and resilient.",
    "You are making a difference in the world.",
    "You are capable of handling whatever comes your way.",
    "You are a source of joy and happiness.",
    "You have a kind and compassionate heart.",
    "You are loved and appreciated.",
    "You have the power to create positive change.",
    "You are enough just as you are.",
    "You are exactly where you need to be right now.",
    "You are full of potential and possibilities.",
    "You have the power to make today a great day.",
    "You are strong, brave, and resilient.",
    "You are a beacon of light and hope.",
    "You are worthy of all the good things in life.",
    "You are capable of amazing things.",
    "You have a lot to offer the world.",
    "You are a valuable and important person.",
    "You have the power to change your story.",
    "You are in control of your own happiness.",
    "You are constantly growing and evolving.",
    "You are a beautiful person inside and out.",
    "Your courage is admirable.",
    "You have the ability to make a positive impact.",
    "You are a source of inspiration to others.",
    "Your hard work and dedication will pay off.",
    "You are a work in progress, and that's okay.",
    "Every step you take brings you closer to your goals.",
    "You are surrounded by love and support.",
    "Believe in the power of your dreams.",
    "You are resilient and can handle anything.",
    "You are deserving of happiness and success.",
    "You are enough just as you are.",
    "Your positive attitude brings good things into your life.",
    "Be kind to yourself and others.",
    "Your potential is limitless.",
    "You have the strength to overcome any challenge.",
    "Embrace your uniqueness; you are one of a kind.",
    "You are worthy of love and respect.",
    "You have the power to create the life you desire.",
    "Every day is a new opportunity to grow and improve.",
    "Believe in yourself and all that you are.",
    "You are capable of achieving great things.",
    "You have the strength to rise above.",
    "Your inner light shines brightly.",
    "You can achieve anything you set your mind to.",
    "Your possibilities are endless.",
    "You are confident and capable.",
    "You have a kind and loving heart.",
    "Your life is full of love and joy.",
    "You are blessed with abundance.",
    "You are strong and unstoppable.",
    "You are worthy of all the best things in life.",
    "You are a magnificent being.",
    "You are a radiant being of light.",
    "You are worthy of all the success and abundance in the world.",
    "You are an amazing individual.",
    "You are confident in your abilities.",
    "You are a source of endless inspiration.",
    "You are a remarkable person.",
    "You are loved more than you know.",
    "You are destined for greatness.",
    "You are full of great ideas.",
    "You are a treasure to those around you.",
    "You are loved and cherished.",
    "You are important and special.",
    "You bring out the best in others.",
    "You are capable of incredible things.",
    "You are strong and courageous.",
    "You are a beautiful person.",
    "You have a beautiful soul.",
    "You are powerful and capable.",
    "You are a positive influence.",
    "You are a gift to the world.",
    "You are full of potential and greatness.",
    "You are cherished and adored.",
    "You are strong and empowered.",
    "You are a beacon of positivity.",
    "You are a source of endless inspiration.",
    "You are unique and irreplaceable.",
    "You are full of life and energy.",
    "You are a blessing to those around you.",
    "You are capable of achieving your goals.",
    "You are a wonderful person.",
    "You are strong and determined.",
    "You are a positive thinker.",
    "You are surrounded by love and positivity.",
    "You are a bright light in the world.",
    "You are strong and capable.",
    "You are a positive force in the world.",
    "You are worthy of all the good things in life.",
    "You are full of potential and greatness.",
    "You are capable of amazing things.",
    "You are a wonderful person.",
    "You are unique and special.",
    "You are a positive and inspiring person.",
    "You are a source of light and positivity.",
    "You are a valuable and important person.",
    "You are capable of achieving great things.",
    "You are worthy of all the success and happiness in the world.",
    "You are a positive force in the world.",
    "You are loved and appreciated.",
    "You are strong and resilient.",
    "You are capable of overcoming any challenge.",
    "You are a wonderful person who deserves the best.",
    "You are a source of joy and happiness.",
    "You are a positive influence on those around you.",
    "You are a beacon of light and hope.",
    "You are a valuable and cherished person.",
    "You are a wonderful individual.",
    "You are full of potential and possibilities.",
    "You are capable of achieving your dreams.",
    "You are a source of strength and hope.",
    "You are a positive thinker and doer.",
    "You are a wonderful person just the way you are.",
    "You have the power to create positive change in your life.",
    "You are loved and valued.",
    "You are a bright light in the world.",
    "You are a source of love and positivity.",
    "You are a positive and powerful force in the world.",
    "You are a wonderful friend.",
    "You are a source of light and inspiration.",
    "You are a positive thinker.",
    "You are braver than you believe.",
    "You are more talented than you know.",
    "You are capable of more than you imagine.",
    "You are a positive and powerful force in the world.",
    "You are a wonderful person with many talents.",
    "You are a valuable friend.",
    "You are a source of joy and happiness.",
    "You are a positive influence on those around you.",
    "You have the ability to brighten someone's day.",
    "You are a wonderful person just the way you are.",
    "You have the power to make your dreams a reality.",
    "You are full of creativity and ideas.",
    "You are deserving of success and happiness.",
    "You are a unique and special individual.",
    "You have the strength to keep going.",
    "You are loved and valued.",
    "You are capable of overcoming any obstacle.",
    "You are a positive force in the world.",
    "You have a bright future ahead of you.",
    "You are a wonderful person.",
    "You are constantly learning and growing.",
    "You are deserving of all the love and happiness in the world.",
    "You have the power to achieve your dreams.",
    "You are strong, capable, and resilient.",
    "You are making a difference in the world.",
    "You are capable of handling whatever comes your way.",
    "You are a source of joy and happiness.",
    "You have a kind and compassionate heart.",
    "You are loved and appreciated.",
    "You have the power to create positive change.",
    "You are enough just as you are.",
    "You are exactly where you need to be right now.",
    "You are full of potential and possibilities.",
    "You have the power to make today a great day.",
    "You are strong, brave, and resilient.",
    "You are a beacon of light and hope.",
    "You are worthy of all the good things in life.",
    "You are capable of amazing things.",
    "You have a lot to offer the world.",
    "You are a valuable and important person.",
    "You have the power to change your story.",
    "You are in control of your own happiness.",
    "You are constantly growing and evolving.",
    "You are a beautiful person inside and out.",
    "Your courage is admirable.",
    "You have the ability to make a positive impact.",
    "You are a source of inspiration to others.",
    "Your hard work and dedication will pay off.",
    "You are a work in progress, and that's okay.",
    "Every step you take brings you closer to your goals.",
    "You are surrounded by love and support.",
    "Believe in the power of your dreams.",
    "You are resilient and can handle anything.",
    "You are deserving of happiness and success.",
    "You are enough just as you are.",
    "Your positive attitude brings good things into your life.",
    "Be kind to yourself and others.",
    "Your potential is limitless.",
    "You have the strength to overcome any challenge.",
    "Embrace your uniqueness; you are one of a kind.",
    "You are worthy of love and respect.",
    "You have the power to create the life you desire.",
    "Every day is a new opportunity to grow and improve.",
    "Believe in yourself and all that you are.",
    "You are capable of achieving great things.",
];

const affirmationElement = document.getElementById('affirmation');
const newAffirmationButton = document.getElementById('new-affirmation-button');

function getDailyAffirmation() {
    const date = new Date();
    const dayOfYear = Math.floor((date - new Date(date.getFullYear(), 0, 0)) / 1000 / 60 / 60 / 24);
    return affirmations[dayOfYear % affirmations.length];
}

function getRandomAffirmation() {
    const randomIndex = Math.floor(Math.random() * affirmations.length);
    return affirmations[randomIndex];
}

function displayAffirmation() {
    affirmationElement.textContent = getDailyAffirmation();
}

function animateAffirmationChange() {
    affirmationElement.classList.add('hidden');
    setTimeout(() => {
        affirmationElement.textContent = getRandomAffirmation();
        affirmationElement.classList.remove('hidden');
    }, 1000); // Time for the animation to complete
}

newAffirmationButton.addEventListener('click', animateAffirmationChange);

displayAffirmation();

